app = "portfolio-frontend-nameless-brook-4052"
primary_region = "arn"

[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 4173
  protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[http_service]
  internal_port = 4173
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
